{
 "title": "Global Hub - What's Changed / Clusters",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "postgres" },
   {
    "name": "hub",
    "label": "Hub",
    "query": "  SELECT DISTINCT leaf_hub_name\n  FROM\n  history.local_compliance ch\n  WHERE\n  $__timeFilter(ch.compliance_date)\n"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "WITH compcluster as(\n  SELECT DISTINCT cluster_id\n  FROM\n  history.local_compliance\n  WHERE\n  $__timeFilter(compliance_date)\n  AND\n  leaf_hub_name = '$hub'\n)\nSELECT\n  cluster_name\nFROM\n  status.managed_clusters mc\nINNER JOIN\n  compcluster ch ON mc.cluster_id = ch.cluster_id"
   },
   {
    "name": "top",
    "label": "Top",
    "query": "SELECT\n '1:5',\nCASE WHEN $maxtop > 5 THEN '$leftmaxtop:$maxtop'\nEND "
   },
   {
    "name": "topleft",
    "query": "SELECT SPLIT_PART('$top', ':', 1);"
   },
   {
    "name": "topright",
    "query": "SELECT SPLIT_PART('$top', ':', 2);"
   },
   {
    "name": "maxtop",
    "query": "WITH clusterid as(\nSELECT\n  DISTINCT cluster_id\nFROM\n  status.managed_clusters\nWHERE\n leaf_hub_name = '$hub'\nAND\n cluster_name = '$cluster'\n),\ncompcluster as(\n  SELECT DISTINCT lc.policy_id\n  FROM\n    history.local_compliance lc\n JOIN\n    clusterid ci\n ON\n   ci.cluster_id = lc.cluster_id\n WHERE\n  $__timeFilter(compliance_date)\n)\nSELECT COUNT(*) \nFROM \n  compcluster\n\n"
   },
   { "name": "leftmaxtop", "query": "select $maxtop-4" },
   {
    "name": "hubConsoleURL",
    "query": "SELECT\n  console_url\nFROM\n  status.leaf_hubs\nwhere\n  leaf_hub_name = '$hub'"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance lc\n  WHERE\n  $__timeFilter(lc.compliance_date)\n  AND\n  leaf_hub_name = '$hub'\n  AND\n  lc.cluster_id IS NOT NULL\n)\nSELECT\n  p.payload -> 'metadata' ->> 'namespace'\nFROM\n  local_spec.policies p\nINNER JOIN\n  compcluster ch ON p.policy_id = ch.policy_id"
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance lc\n  WHERE\n  $__timeFilter(lc.compliance_date)\n  AND\n  leaf_hub_name = '$hub'\n)\nSELECT\n  policy_name\nFROM\n  local_spec.policies p\nINNER JOIN\n  compcluster ch ON p.policy_id = ch.policy_id\nWHERE\n  p.payload -> 'metadata' ->> 'namespace' in ($namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Policy State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH data as (\n  SELECT \n    $__timeGroupAlias(lc.compliance_date, $__interval),\n    p.policy_name,\n    CASE WHEN lc.compliance = 'non_compliant' THEN 2\n         WHEN lc.compliance = 'unknown' THEN 1\n         WHEN lc.compliance = 'compliant' THEN 0\n    END AS \"compliance\"\n  FROM\n    history.local_compliance lc\n  INNER JOIN\n    local_spec.policies p ON lc.policy_id = p.policy_id\n  INNER JOIN\n    status.managed_clusters mc ON lc.cluster_id = mc.cluster_id\n  WHERE\n    $__timeFilter(lc.compliance_date)\n  AND\n    mc.cluster_name = '$cluster'\n  AND \n    lc.leaf_hub_name = '$hub'\n  AND\n    p.payload -> 'metadata' ->> 'namespace' in ($namespace)\n  AND\n    p.policy_name in ($policy)\n),\norderclusters as (\n  SELECT\n    policy_name,\n    ROW_NUMBER () OVER (ORDER BY SUM(compliance) DESC) as row_number\n  FROM\n    data\n  GROUP BY(policy_name)\n)\nSELECT\n  time,\n  dc.policy_name as \"metric\",\n  compliance as \"value\"\nFROM\n  orderclusters tc\nJOIN\n  data dc on dc.policy_name = tc.policy_name\nWHERE\n  tc.row_number >= $topleft AND tc.row_number <= $topright\nORDER BY (time)"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Policy Propagation Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  rp.created_at as \"time\",\n  p.leaf_hub_name as \"hub\",\n  p.payload -> 'metadata' ->> 'namespace' as \"namespace\",\n  p.policy_name,\n  rp.message\nFROM\n  event.local_root_policies rp\nINNER JOIN\n  local_spec.policies p ON rp.policy_id = p.policy_id\nWHERE\n  $__timeFilter(rp.created_at)\nAND\n  p.leaf_hub_name = '$hub'\nAND\n  rp.message LIKE '%$cluster/%'\nAND\n  p.payload -> 'metadata' ->> 'namespace' in ($namespace)\nAND\n  p.policy_name in ($policy)\nORDER BY (rp.created_at) DESC"
    }
   ]
  },
  {
   "title": "Policy Compliance Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  lp.created_at as \"time\",\n  p.leaf_hub_name as \"hub\",\n  p.payload -> 'metadata' ->> 'namespace' as namespace,\n  p.policy_name,\n  mc.cluster_name,\n  lp.message,\n  lp.reason,\n  lp.compliance\nFROM\n  event.local_policies lp\nINNER JOIN\n  local_spec.policies p ON lp.policy_id = p.policy_id\nINNER JOIN\n  status.managed_clusters mc ON lp.cluster_id = mc.cluster_id\nWHERE\n  $__timeFilter(lp.created_at)\nAND\n  mc.leaf_hub_name = '$hub'\nAND\n  mc.cluster_name = '$cluster'\nAND\n  p.payload -> 'metadata' ->> 'namespace' in ($namespace)\nAND\n  p.policy_name in ($policy)\nORDER BY (lp.created_at,lp.compliance) DESC"
    }
   ]
  }
 ]
}