apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-global-hub-grafana
  name: multicluster-global-hub-grafana
  namespace: {{.Namespace}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-grafana-tls
spec:
  ports:
  - name: oauth-proxy
    port: 9443
    protocol: TCP
    targetPort: 9443
  - name: grafana
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    name: multicluster-global-hub-grafana
  type: ClusterIP