apiVersion: v1
kind: Service
metadata:
  name: multicluster-global-hub-webhook
  namespace: multicluster-global-hub
  labels:
    name: multicluster-global-hub-webhook
    service: multicluster-global-hub-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-webhook-certs
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
    name: webhook-server
  selector:
    name: multicluster-global-hub-operator
