apiVersion: v1
kind: Secret
metadata:
  name: {{.TransportConfigSecret}}
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
type: Opaque
data:
  {{- if .KafkaConfigYaml }}
  "kafka.yaml": {{.KafkaConfigYaml}}
  {{- end }}
  {{- if .InventoryConfigYaml }}
  "rest.yaml": {{.InventoryConfigYaml}}
  {{- end }}
