apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-global-hub-operator
  namespace: multicluster-global-hub
spec:
  template:
    spec:
      containers:
      - name: multicluster-global-hub-operator
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          defaultMode: 420
          secretName: multicluster-global-hub-webhook-certs
